#!/bin/bash 
#SBATCH --job-name=foldx    # Job name                                         
#SBATCH --mail-type=ALL          # Mail events (NONE, BEGIN, END, FAIL, ALL)                   
#SBATCH --mail-user=vjonsson@caltech.edu     # Where to send mail              
#SBATCH -n 2                         # Number of cores                                     
#SBATCH -N 1-2                        # Min - Max Nodes                      
#SBATCH -p all                        # default queue is all if you don't specify  
#SBATCH --mem=32G                      # Amount of memory in GB                   
#SBATCH --time=10:00:00               # Time limit hrs:min:sec       
#SBATCH --output=foldx.log   # Standard output and error log  

module load FoldX
module load Python/3.8.1-foss-2018b

echo 'about to run foldx'                                                          
foldx --command=RepairPDB --pdb='6xcm.pdb' --out-pdb=true          
echo 'done repairing'   

python antibody_pipeline.py